import "../styles/globals.css";
import Header from "../components/Header";

import { appWithTranslation } from "next-i18next";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>SA2GE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header will go on every page */}
      <Header />
      {/* Main App */}
      <Component {...pageProps} />
    </>
  );
}

export default appWithTranslation(MyApp);
